- added code from internal repository
ravendb/ravendb-nodejs-client pull request #1
Opened 2017-03-07 12:59 UTC by mobilunity-user

2017-03-07 13:55 UTC, gregolsky requested changes

2017-03-07 13:55 UTC, gregolsky commented on package.json
> +  "name": "ravendb-node",
Let's change the name of the package to `ravendb-client`.

2017-03-07 13:55 UTC, gregolsky commented on package.json
> +  "author": "Hybernating Rhinos",
A typo here. It's *Hibernating Rhinos*

2017-03-07 13:55 UTC, gregolsky commented on package.json
> +    "url": "git@git.devs.domerp.com:frontend-projects/ravendb-node.git"
Please change the url to https://github.com/ravendb/ravendb-nodejs-client

2017-03-07 13:55 UTC, gregolsky commented on package.json
> +  "license": "ISC",
Please set the `license` field to [match the one set on the repository](https://github.com/ravendb/ravendb-nodejs-client/blob/v4.0/LICENSE).

2017-03-07 13:55 UTC, gregolsky commented on tsconfig.json
> +    "target": "es5",
target mismatch with https://github.com/ravendb/ravendb-nodejs-client/pull/1/commits/b0919fb7aa07a8f95cf7c3cdf0ebbe3684e155be#diff-601a9423323a9d2a4fd0c9b51b5ae4caR42

2017-03-07 13:55 UTC, gregolsky commented on src/Documents/DocumentStore.ts
> +
Let's use the following style conventions for Typescript code in this project:

Use PascalCase for class and interface names.
Use PascalCase for enum values.
Use camelCase for function names.
Use camelCase for property names and local variables.
Use camelCase for argument names.
Use "_" as a prefix for `private` properties (not for `protected` ones).
Use camelCase for file / module names;

2017-03-07 13:55 UTC, gregolsky commented on src/Documents/DocumentStore.ts
> +  public get RequestExecutor(): RequestExecutor
Please keep one bracket opening/closing convention - opening brackets on line end and closing ones in new lines.

2017-03-07 13:55 UTC, gregolsky commented on scripts/build-bundle.js
> +fs.writeFileSync(bundle, allContents, { encoding: 'utf8', flag: 'a' });
Are we going to convert this to `gulp` tasks ?

2017-03-08 06:09 UTC, ayende commented on src/Documents/Document.ts
> +
Would we need serialize / deserialize? We are working on JS, after all. We can just do `JSON.serialize` and vice versa and get the same behavior, no?

2017-03-08 07:50 UTC, gregolsky commented on src/Documents/Document.ts
> +
We probably do not need a class nor interface for `Document` at all. `Raven.Client` (C#) does not have a concept of document. It just returns objects/entities. We could just use `JSON.parse()` on the document body from server's response and `JSON.serialize()` if we need a string representation.

2017-03-08 07:52 UTC, ayende commented on src/Documents/Document.ts
> +
Agree, we should be able to accept any JS object here.

2017-03-09 18:11 UTC, gregolsky commented on src/Documents/Document.ts
> +
@a-serdukov-mobilunity please adjust the code based on our above comments. If you have any questions concerning this change let's talk tomorrow.

2017-03-09 18:12 UTC, gregolsky commented
@a-serdukov-mobilunity Please fix the conflicts with LICENSE file. Thanks.

2017-03-09 19:45 UTC, ayende commented
We need to pull this already, so there is _something_ that we can start with

2017-03-10 07:15 UTC, gregolsky commented
@ayende OK, I've rebased changes and created PR #2 . We should close this one.

2017-03-10 07:18 UTC, closed without merging

2017-03-10 09:32 UTC, mobilunity-user commented on src/Documents/Document.ts
> +
how i should serialize them ?
your Pythin client accepts any objects, it also support linked documents where the property is a another class

also, a lot of mongo clients has own models classes with validation, relations etc
i would use IDocument/Document based on Backbone Model

2017-03-10 11:46 UTC, ayende commented on src/Documents/Document.ts
> +
`JSON.serialize` should handle it, no?
And validation is something that you do outside of the object, using listeners, for example.