build errors fixes
ravendb/ravendb-nodejs-client pull request #14
Opened 2017-06-21 10:54 UTC by mobilunity-user

2017-06-21 11:37 UTC, gregolsky commented on package.json
> +    "typescript": "^2.3.4",
Just `2.3.4` - without the dash `^`.

2017-06-21 13:45 UTC, gregolsky requested changes

2017-06-21 13:45 UTC, gregolsky commented on package.json
> +    "typescript": "^2.3.4",
"typescript": "2.3.x". Otherwise it's still going to install 2.4 for node 8.

2017-06-22 09:19 UTC, mobilunity-user commented on package.json
> +    "typescript": "^2.3.4",
done

2017-06-22 09:32 UTC, gregolsky requested changes

2017-06-22 09:32 UTC, gregolsky commented on package.json
> +    "typescript": "2.3.*",
Almost :) `*` means *any* version. Make it `~2.3.4`, which means only *patch* number (last one) can increment.

2017-06-22 10:42 UTC, mobilunity-user commented on package.json
> +    "typescript": "2.3.*",
ok

2017-06-22 10:45 UTC, merged